"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import Link from "next/link";
import { useTranslations } from "next-intl";
import { useQueryClient } from "@tanstack/react-query";
import {
  Ban,
  CheckCircle2,
  Circle as CircleIcon,
  Hexagon,
  Loader2,
  MapPin,
  Trash2,
  Upload,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { ToggleChip } from "@/components/app/toggle-chip";
import { useAuth } from "@/contexts/auth-context";
import { canManageRestaurants } from "@/lib/auth/permissions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import { queryKeys } from "@/lib/query/query-keys";
import type { ZoneGeometryType, ZoneGeoFeature } from "@/lib/geo/zone-geometry";
import type { ZoneMapTool } from "@/features/zones/zone-form-map-toolbar";
import {
  deleteRestaurant,
  fetchRestaurantGeofences,
  saveRestaurant,
  saveRestaurantGeofences,
} from "./restaurants-actions";
import { isRestaurantErrorKey } from "./restaurant-errors";
import { validateExternalMerchantId } from "./external-merchant-id";
import { draftGeofencesToInput } from "./restaurant-geofence-utils";
import { RestaurantFormFields } from "./restaurant-form-fields";
import { RestaurantGeofenceList } from "./restaurant-geofence-list";
import {
  RestaurantGeofenceMap,
  type RestaurantMapMode,
} from "./restaurant-geofence-map";
import { isRestaurantGeofenceErrorKey } from "./restaurant-geofence-errors";
import {
  googleMapsUrlFromCoords,
  isAutoGeneratedMapLink,
  locationFromRestaurant,
  type RestaurantLocation,
} from "./restaurant-location-utils";
import type { RestaurantStatus } from "./restaurant-status";
import type {
  RestaurantGeofenceDraft,
  RestaurantGeofenceKind,
  RestaurantRow,
} from "./types";
import {
  useRestaurantPartnerOptions,
  useRestaurantZoneOptions,
} from "./use-restaurants";

function errorToast(
  t: ReturnType<typeof useTranslations<"pages.restaurants">>,
  error?: string,
) {
  if (error && isRestaurantErrorKey(error)) return t(`errors.${error}`);
  return t("errors.save_failed");
}

function geofenceErrorToast(
  t: ReturnType<typeof useTranslations<"pages.restaurants">>,
  error?: string,
) {
  if (error && isRestaurantGeofenceErrorKey(error)) {
    return t(`geofences.errors.${error}`);
  }
  return t("geofences.errors.save_failed");
}

function newTempGeofenceId() {
  return `temp-${crypto.randomUUID()}`;
}

export function RestaurantFormBody({
  restaurant,
  onClose,
  onSaved,
  onRequestDelete,
}: {
  restaurant: RestaurantRow | null;
  onClose: () => void;
  onSaved: () => void;
  onRequestDelete: () => void;
}) {
  const t = useTranslations("pages.restaurants");
  const { permissions, isSuperAdmin } = useAuth();
  const canManage = canManageRestaurants(new Set(permissions), isSuperAdmin);
  const queryClient = useQueryClient();
  const [isPending, startTransition] = useTransition();
  const fileRef = useRef<HTMLInputElement>(null);
  const { data: partners = [], isLoading: partnersLoading } =
    useRestaurantPartnerOptions();
  const { data: zones = [], isLoading: zonesLoading } = useRestaurantZoneOptions();

  const isEdit = Boolean(restaurant);

  const [partnerId, setPartnerId] = useState(restaurant?.partner_id ?? "");
  const [zoneId, setZoneId] = useState(restaurant?.zone_id ?? "");
  const [name, setName] = useState(restaurant?.name ?? "");
  const [externalMerchantId, setExternalMerchantId] = useState(
    restaurant?.external_merchant_id ?? "",
  );
  const [mapLink, setMapLink] = useState(restaurant?.map_link ?? "");
  const [location, setLocation] = useState<RestaurantLocation | null>(() =>
    locationFromRestaurant(restaurant?.latitude, restaurant?.longitude),
  );
  const [status, setStatus] = useState<RestaurantStatus>(
    restaurant?.status ?? "draft",
  );
  const [logoPreview, setLogoPreview] = useState<string | null>(
    restaurant?.logo_display_url ?? null,
  );
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [removeLogo, setRemoveLogo] = useState(false);

  const [geofences, setGeofences] = useState<RestaurantGeofenceDraft[]>([]);
  const [geofencesLoading, setGeofencesLoading] = useState(isEdit);
  const [selectedGeofenceId, setSelectedGeofenceId] = useState<string | null>(
    null,
  );
  const [drawKind, setDrawKind] = useState<RestaurantGeofenceKind>("inclusion");
  const [zoneType, setZoneType] = useState<ZoneGeometryType>("polygon");
  const [mapMode, setMapMode] = useState<RestaurantMapMode>("pin");
  const [activeTool, setActiveTool] = useState<ZoneMapTool>("draw");
  const [mapPanelOpen, setMapPanelOpen] = useState(true);

  useEffect(() => {
    if (!restaurant?.id) {
      setGeofences([]);
      setGeofencesLoading(false);
      return;
    }

    let cancelled = false;
    setGeofencesLoading(true);
    fetchRestaurantGeofences(restaurant.id)
      .then((rows) => {
        if (cancelled) return;
        setGeofences(
          rows.map((row) => ({
            id: row.id,
            kind: row.kind,
            zone_type: row.zone_type,
            geometry: row.geometry,
            name: row.name,
            color: row.color,
          })),
        );
      })
      .catch(() => {
        if (!cancelled) toast.error(t("geofences.errors.load_failed"));
      })
      .finally(() => {
        if (!cancelled) setGeofencesLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [restaurant?.id, t]);

  useEffect(() => {
    return () => {
      if (logoPreview?.startsWith("blob:")) {
        URL.revokeObjectURL(logoPreview);
      }
    };
  }, [logoPreview]);

  const handleLogoChange = (file: File | null) => {
    if (!file) return;
    setLogoFile(file);
    setRemoveLogo(false);
    if (logoPreview?.startsWith("blob:")) URL.revokeObjectURL(logoPreview);
    setLogoPreview(URL.createObjectURL(file));
  };

  const fieldLabels = {
    partner: t("fields.partner"),
    zone: t("fields.zone"),
    name: t("fields.name"),
    externalMerchantId: t("fields.externalMerchantId"),
    externalMerchantIdHint: t("hints.externalMerchantId"),
    mapLink: t("fields.mapLink"),
    mapLinkHint: t("hints.mapLink"),
    mapAutoFilledHint:
      mapLink.trim() && isAutoGeneratedMapLink(mapLink)
        ? t("hints.mapAutoFilled")
        : undefined,
    status: t("fields.status"),
    statusHint: t("hints.status"),
    selectPartner: t("placeholders.selectPartner"),
    selectZone: t("placeholders.selectZone"),
    selectNone: t("placeholders.selectNone"),
    namePlaceholder: t("placeholders.name"),
    mapLinkPlaceholder: t("placeholders.mapLink"),
    statusDraft: t("statusDraft"),
    statusPublished: t("statusPublished"),
    statusArchived: t("statusArchived"),
    coordinatesSection: t("fields.coordinates"),
    coordinatesLatitude: t("fields.latitude"),
    coordinatesLongitude: t("fields.longitude"),
    coordinatesHint: t("hints.coordinates"),
    coordinatesInvalidLatitude: t("hints.invalidLatitude"),
    coordinatesInvalidLongitude: t("hints.invalidLongitude"),
  };

  const handleLocationChange = (next: RestaurantLocation | null) => {
    setLocation(next);
    if (next && isAutoGeneratedMapLink(mapLink)) {
      setMapLink(googleMapsUrlFromCoords(next.lat, next.lng));
    }
  };

  const invalidate = () => {
    void queryClient.invalidateQueries({ queryKey: queryKeys.restaurants.all() });
    void queryClient.invalidateQueries({
      queryKey: [...queryKeys.drivers.all(), "form-options"],
    });
    void queryClient.invalidateQueries({ queryKey: queryKeys.dpd.all() });
  };

  const handleAddGeofence = (
    draft: Omit<RestaurantGeofenceDraft, "id">,
  ) => {
    const id = newTempGeofenceId();
    setGeofences((current) => [...current, { ...draft, id }]);
    setSelectedGeofenceId(id);
    setMapMode("draw");
    setActiveTool("edit");
  };

  const handleGeofenceChange = (
    id: string,
    geometry: ZoneGeoFeature,
    nextZoneType: ZoneGeometryType,
  ) => {
    setGeofences((current) =>
      current.map((item) =>
        item.id === id
          ? { ...item, geometry, zone_type: nextZoneType }
          : item,
      ),
    );
  };

  const handleDeleteGeofence = (id: string) => {
    setGeofences((current) => current.filter((item) => item.id !== id));
    if (selectedGeofenceId === id) setSelectedGeofenceId(null);
  };

  const inclusionGeofenceCount = geofences.filter(
    (g) => g.kind === "inclusion",
  ).length;
  const hasLocationProof = location !== null || inclusionGeofenceCount > 0;
  const wantsToPublishWithoutLocation =
    status === "published" && !hasLocationProof;

  const handleSave = () => {
    if (!name.trim()) {
      toast.error(t("errors.missing_fields"));
      return;
    }
    const merchantError = validateExternalMerchantId(externalMerchantId);
    if (merchantError) {
      toast.error(t("errors.invalid_external_merchant_id"));
      return;
    }

    startTransition(async () => {
      const formData = new FormData();
      if (restaurant?.id) formData.append("id", restaurant.id);
      formData.append("partnerId", partnerId);
      formData.append("zoneId", zoneId);
      formData.append("name", name);
      formData.append("externalMerchantId", externalMerchantId);
      formData.append("mapLink", mapLink);
      formData.append("status", status);
      formData.append(
        "inclusionGeofenceCount",
        String(inclusionGeofenceCount),
      );
      if (location) {
        formData.append("latitude", String(location.lat));
        formData.append("longitude", String(location.lng));
      } else {
        formData.append("latitude", "");
        formData.append("longitude", "");
      }
      if (logoFile) formData.append("logo", logoFile);
      if (removeLogo) formData.append("removeLogo", "true");

      const result = await saveRestaurant(formData);
      if (result.error) {
        toast.error(errorToast(t, result.error), {
          description: result.errorDetail,
          duration: result.errorDetail ? 8000 : 4000,
        });
        return;
      }

      const restaurantId = result.id ?? restaurant?.id;
      if (restaurantId) {
        const geofenceResult = await saveRestaurantGeofences(
          restaurantId,
          draftGeofencesToInput(geofences),
        );
        if (geofenceResult.error) {
          toast.error(geofenceErrorToast(t, geofenceResult.error));
          return;
        }
      }

      if (result.logoWarning && isRestaurantErrorKey(result.logoWarning)) {
        toast.warning(t(`errors.${result.logoWarning}`));
      }
      if (result.statusWarning === "auto_downgraded_to_draft") {
        if (result.finalStatus) setStatus(result.finalStatus);
        toast.warning(t("warnings.auto_downgraded_to_draft"), {
          description: t("warnings.auto_downgraded_to_draft_description"),
          duration: 6000,
        });
      } else {
        toast.success(isEdit ? t("restaurantUpdated") : t("restaurantCreated"));
      }
      invalidate();
      onSaved();
      onClose();
    });
  };

  const kindItems: Array<{
    kind: RestaurantGeofenceKind;
    Icon: typeof CheckCircle2;
  }> = [
    { kind: "inclusion", Icon: CheckCircle2 },
    { kind: "exclusion", Icon: Ban },
  ];

  const shapeItems: Array<{
    shape: ZoneGeometryType;
    Icon: typeof Hexagon;
  }> = [
    { shape: "polygon", Icon: Hexagon },
    { shape: "circle", Icon: CircleIcon },
  ];

  return (
    <div
      className={cn(
        "grid min-h-0 flex-1 grid-cols-1 gap-3 overflow-hidden",
        mapPanelOpen && "lg:grid-cols-[minmax(340px,380px)_minmax(0,1fr)]",
      )}
    >
      <aside className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900">
        <header className="space-y-1 border-b border-slate-200 px-4 py-3 dark:border-slate-700">
          <p className="text-[11px] font-medium text-slate-500 dark:text-slate-400">
            <Link href="/restaurants" className="hover:text-primary hover:underline">
              {t("title")}
            </Link>
            <span className="px-1.5 text-slate-300">/</span>
            <span className="text-slate-700 dark:text-slate-200">
              {isEdit ? t("editRestaurant") : t("addRestaurant")}
            </span>
          </p>
          <h1 className="text-base font-semibold text-slate-900 dark:text-slate-50">
            {isEdit ? t("editRestaurant") : t("addRestaurant")}
          </h1>
        </header>

        <div className="min-h-0 flex-1 space-y-4 overflow-y-auto px-4 py-4">
          <div className="space-y-2">
            <Label>{t("fields.logo")}</Label>
            <div className="flex items-start gap-4">
              <div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-border bg-muted/40">
                {logoPreview && !removeLogo ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={logoPreview}
                    alt=""
                    className="h-full w-full object-contain p-1"
                  />
                ) : (
                  <span className="text-[10px] text-muted-foreground">
                    {t("noLogo")}
                  </span>
                )}
              </div>
              <div className="flex flex-col gap-2">
                <input
                  ref={fileRef}
                  type="file"
                  accept="image/png,image/jpeg,image/webp,image/svg+xml"
                  className="hidden"
                  onChange={(e) => handleLogoChange(e.target.files?.[0] ?? null)}
                />
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  className="cursor-pointer rounded-lg"
                  onClick={() => fileRef.current?.click()}
                  disabled={!canManage}
                >
                  <Upload className="me-2 h-3.5 w-3.5" />
                  {t("uploadLogo")}
                </Button>
                {logoPreview && !removeLogo && canManage ? (
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="cursor-pointer text-destructive hover:text-destructive"
                    onClick={() => {
                      setRemoveLogo(true);
                      setLogoFile(null);
                      setLogoPreview(null);
                    }}
                  >
                    {t("removeLogo")}
                  </Button>
                ) : null}
              </div>
            </div>
            <p className="text-[11px] text-muted-foreground">{t("hints.logo")}</p>
          </div>

          <RestaurantFormFields
            labels={fieldLabels}
            partnerId={partnerId}
            zoneId={zoneId}
            name={name}
            externalMerchantId={externalMerchantId}
            mapLink={mapLink}
            status={status}
            location={location}
            partners={partners}
            zones={zones}
            partnersLoading={partnersLoading}
            zonesLoading={zonesLoading}
            onPartnerIdChange={setPartnerId}
            onZoneIdChange={setZoneId}
            onNameChange={setName}
            onExternalMerchantIdChange={setExternalMerchantId}
            onMapLinkChange={setMapLink}
            onStatusChange={setStatus}
            onLocationChange={handleLocationChange}
          />

          {wantsToPublishWithoutLocation ? (
            <p className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-[11px] leading-snug text-amber-900 dark:border-amber-500/40 dark:bg-amber-500/10 dark:text-amber-100">
              {t("hints.publishRequiresLocation")}
            </p>
          ) : null}

          {!partnersLoading && partners.length === 0 ? (
            <p className="text-[11px] text-muted-foreground">
              {t("errors.noPartners")}
            </p>
          ) : null}
          {!zonesLoading && zones.length === 0 ? (
            <p className="text-[11px] text-muted-foreground">
              {t("errors.noZones")}
            </p>
          ) : null}

          <div className="space-y-2 border-t border-border pt-4">
            <Label className="text-xs font-semibold text-foreground">
              {t("geofences.kindTitle")}
            </Label>
            <div className="flex flex-wrap gap-2">
              {kindItems.map(({ kind, Icon }) => (
                <ToggleChip
                  key={kind}
                  selected={drawKind === kind}
                  icon={Icon}
                  onClick={() => {
                    setDrawKind(kind);
                    setMapMode("draw");
                    setActiveTool("draw");
                  }}
                >
                  {t(`geofences.kind.${kind}`)}
                </ToggleChip>
              ))}
            </div>
          </div>

          <div className="space-y-2">
            <Label className="text-xs font-semibold text-foreground">
              {t("geofences.shapeTitle")}
            </Label>
            <div className="grid grid-cols-2 gap-2">
              {shapeItems.map(({ shape, Icon }) => {
                const active = zoneType === shape;
                return (
                  <button
                    key={shape}
                    type="button"
                    onClick={() => {
                      setZoneType(shape);
                      setMapMode("draw");
                      setActiveTool("draw");
                    }}
                    className={cn(
                      "flex cursor-pointer flex-col items-start gap-1 rounded-lg border p-2.5 text-start transition-colors",
                      active
                        ? "border-primary bg-primary/5"
                        : "border-border bg-card hover:border-primary/40",
                    )}
                  >
                    <Icon
                      className={cn(
                        "h-4 w-4",
                        active ? "text-primary" : "text-muted-foreground",
                      )}
                    />
                    <span className="text-xs font-semibold">
                      {t(`geofences.shape.${shape}`)}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          {geofencesLoading ? (
            <div className="flex justify-center py-4">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            </div>
          ) : (
            <RestaurantGeofenceList
              geofences={geofences}
              selectedId={selectedGeofenceId}
              onSelect={setSelectedGeofenceId}
              onNameChange={(id, nextName) =>
                setGeofences((current) =>
                  current.map((item) =>
                    item.id === id ? { ...item, name: nextName || null } : item,
                  ),
                )
              }
              onDelete={handleDeleteGeofence}
            />
          )}

          {!mapPanelOpen ? (
            <Button
              type="button"
              variant="outline"
              className="h-9 w-full cursor-pointer rounded-lg"
              onClick={() => setMapPanelOpen(true)}
            >
              <MapPin className="me-2 h-3.5 w-3.5" />
              {t("openLocationMap")}
            </Button>
          ) : null}
        </div>

        <footer className="flex items-center justify-between gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3 dark:border-slate-700 dark:bg-slate-900/60">
          {isEdit && canManage ? (
            <Button
              type="button"
              variant="outline"
              className="h-9 cursor-pointer rounded-lg border-destructive/40 text-destructive hover:bg-destructive/10 hover:text-destructive"
              onClick={onRequestDelete}
              disabled={isPending}
            >
              <Trash2 className="me-2 h-3.5 w-3.5" />
              {t("deleteRestaurant")}
            </Button>
          ) : (
            <Button
              type="button"
              variant="outline"
              className="h-9 cursor-pointer rounded-lg"
              onClick={onClose}
              disabled={isPending}
            >
              {t("cancel")}
            </Button>
          )}
          <div className="flex items-center gap-2">
            {isEdit && canManage ? (
              <Button
                type="button"
                variant="outline"
                className="h-9 cursor-pointer rounded-lg"
                onClick={onClose}
                disabled={isPending}
              >
                {t("cancel")}
              </Button>
            ) : null}
            {canManage ? (
              <Button
                type="button"
                className="h-9 cursor-pointer rounded-lg"
                onClick={handleSave}
                disabled={isPending || !name.trim() || geofencesLoading}
              >
                {isPending ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : isEdit ? (
                  t("save")
                ) : (
                  t("createRestaurant")
                )}
              </Button>
            ) : null}
          </div>
        </footer>
      </aside>

      {mapPanelOpen ? (
        <section
          className={cn(
            "relative min-h-[420px] flex-1 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900",
            "max-lg:fixed max-lg:inset-0 max-lg:z-50 max-lg:min-h-0 max-lg:rounded-none max-lg:border-0",
          )}
        >
          <button
            type="button"
            onClick={() => setMapPanelOpen(false)}
            aria-label={t("closeMap")}
            className="absolute end-3 top-3 z-40 inline-flex h-9 w-9 cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 shadow-md transition-colors hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-slate-800"
          >
            <X className="h-4 w-4" />
          </button>
          <RestaurantGeofenceMap
            location={location}
            onLocationChange={handleLocationChange}
            geofences={geofences}
            selectedGeofenceId={selectedGeofenceId}
            onSelectGeofence={setSelectedGeofenceId}
            onGeofenceChange={handleGeofenceChange}
            onAddGeofence={handleAddGeofence}
            onDeleteGeofence={handleDeleteGeofence}
            drawKind={drawKind}
            zoneType={zoneType}
            mapMode={mapMode}
            onMapModeChange={setMapMode}
            activeTool={activeTool}
            onToolChange={setActiveTool}
            className="h-full w-full"
          />
        </section>
      ) : null}
    </div>
  );
}
