export type RestaurantLocation = {
  lat: number;
  lng: number;
};

export function googleMapsUrlFromCoords(lat: number, lng: number): string {
  return `https://www.google.com/maps?q=${lat},${lng}`;
}

/** True when empty or matches a URL auto-generated from pin coordinates. */
export function isAutoGeneratedMapLink(link: string): boolean {
  const trimmed = link.trim();
  if (!trimmed) return true;
  return /^https:\/\/(www\.)?google\.com\/maps\?q=-?\d+(?:\.\d+)?,-?\d+(?:\.\d+)?$/i.test(
    trimmed,
  );
}

export function locationFromRestaurant(
  latitude: number | null | undefined,
  longitude: number | null | undefined,
): RestaurantLocation | null {
  if (
    latitude == null ||
    longitude == null ||
    !Number.isFinite(latitude) ||
    !Number.isFinite(longitude)
  ) {
    return null;
  }
  return { lat: latitude, lng: longitude };
}

export function isValidLatitude(value: number): boolean {
  return Number.isFinite(value) && value >= -90 && value <= 90;
}

export function isValidLongitude(value: number): boolean {
  return Number.isFinite(value) && value >= -180 && value <= 180;
}

/**
 * Parse a free-form string into a coordinate pair. Supports the common
 * formats users hit:
 *   - "29.3759, 47.9774"  (Google Maps right-click copy)
 *   - "29.3759,47.9774" / "29.3759 47.9774"
 *   - "https://www.google.com/maps?q=29.3759,47.9774"
 *   - "https://www.google.com/maps/@29.3759,47.9774,16z"
 *   - "https://maps.apple.com/?ll=29.3759,47.9774"
 *   - "geo:29.3759,47.9774"
 * Returns null if no valid pair is detected.
 */
export function parseCoordinatePair(input: string): RestaurantLocation | null {
  const text = input.trim();
  if (!text) return null;

  const numberPair = /(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/;

  const queryMatch = text.match(
    /[?&](?:q|ll|sll|daddr|destination)=(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/i,
  );
  if (queryMatch) {
    const lat = parseFloat(queryMatch[1]);
    const lng = parseFloat(queryMatch[2]);
    if (isValidLatitude(lat) && isValidLongitude(lng)) return { lat, lng };
  }

  const atMatch = text.match(/@(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/);
  if (atMatch) {
    const lat = parseFloat(atMatch[1]);
    const lng = parseFloat(atMatch[2]);
    if (isValidLatitude(lat) && isValidLongitude(lng)) return { lat, lng };
  }

  const geoMatch = text.match(/^geo:(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/i);
  if (geoMatch) {
    const lat = parseFloat(geoMatch[1]);
    const lng = parseFloat(geoMatch[2]);
    if (isValidLatitude(lat) && isValidLongitude(lng)) return { lat, lng };
  }

  const bareMatch = text.match(
    /^(-?\d+(?:\.\d+)?)\s*[,\s]\s*(-?\d+(?:\.\d+)?)$/,
  );
  if (bareMatch) {
    const lat = parseFloat(bareMatch[1]);
    const lng = parseFloat(bareMatch[2]);
    if (isValidLatitude(lat) && isValidLongitude(lng)) return { lat, lng };
  }

  // Final fallback: any "num, num" anywhere in a longer URL/string.
  const anywhere = text.match(numberPair);
  if (anywhere) {
    const lat = parseFloat(anywhere[1]);
    const lng = parseFloat(anywhere[2]);
    if (isValidLatitude(lat) && isValidLongitude(lng)) return { lat, lng };
  }

  return null;
}
