config:
  dpd-infra:environment: testing
  # Existing resources (reference only — not created by Pulumi)
  dpd-infra:supabaseProjectRef: ytfmsgckjatiserpgdbz
  dpd-infra:supabaseOrganizationId: likgpozawcekbcqzsstb
  dpd-infra:firebaseProjectId: musallam-delivery-kw
  dpd-infra:r2BucketName: dpd-private
  dpd-infra:cloudflareAccountId: 04c485faa34d67d1758b61465202e9ce
  dpd-infra:vercelProjectId: prj_sONw8XqSHBKRuLe9OyslUebjnCBq
  dpd-infra:vercelTeamId: team_54JuMptqR0dmTTbGza0Iawbx
  dpd-infra:vercelProjectName: dpdadmin
  dpd-infra:appUrl: https://dpdadmin.vercel.app
