// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Apikey extends pulumi.CustomResource {
    /**
     * Get an existing Apikey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApikeyState, opts?: pulumi.CustomResourceOptions): Apikey {
        return new Apikey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'supabase:index/apikey:Apikey';

    /**
     * Returns true if the given object is an instance of Apikey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Apikey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Apikey.__pulumiType;
    }

    /**
     * API key
     */
    declare public /*out*/ readonly apiKey: pulumi.Output<string>;
    /**
     * Description of the API key
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Name of the API key
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Project reference ID
     */
    declare public readonly projectRef: pulumi.Output<string>;
    /**
     * Secret JWT template
     */
    declare public /*out*/ readonly secretJwtTemplate: pulumi.Output<outputs.ApikeySecretJwtTemplate>;
    /**
     * Type of the API key
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;

    /**
     * Create a Apikey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApikeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApikeyArgs | ApikeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApikeyState | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectRef"] = state?.projectRef;
            resourceInputs["secretJwtTemplate"] = state?.secretJwtTemplate;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as ApikeyArgs | undefined;
            if (args?.projectRef === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectRef'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectRef"] = args?.projectRef;
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["secretJwtTemplate"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Apikey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Apikey resources.
 */
export interface ApikeyState {
    /**
     * API key
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * Description of the API key
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Name of the API key
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Project reference ID
     */
    projectRef?: pulumi.Input<string | undefined>;
    /**
     * Secret JWT template
     */
    secretJwtTemplate?: pulumi.Input<inputs.ApikeySecretJwtTemplate | undefined>;
    /**
     * Type of the API key
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Apikey resource.
 */
export interface ApikeyArgs {
    /**
     * Description of the API key
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Name of the API key
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Project reference ID
     */
    projectRef: pulumi.Input<string>;
}
