// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Branch extends pulumi.CustomResource {
    /**
     * Get an existing Branch resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BranchState, opts?: pulumi.CustomResourceOptions): Branch {
        return new Branch(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'supabase:index/branch:Branch';

    /**
     * Returns true if the given object is an instance of Branch.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Branch {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Branch.__pulumiType;
    }

    /**
     * Database connection details
     */
    declare public /*out*/ readonly database: pulumi.Output<outputs.BranchDatabase>;
    /**
     * Git branch
     */
    declare public readonly gitBranch: pulumi.Output<string>;
    /**
     * Parent project ref
     */
    declare public readonly parentProjectRef: pulumi.Output<string>;
    /**
     * Database region
     */
    declare public readonly region: pulumi.Output<string | undefined>;

    /**
     * Create a Branch resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BranchArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BranchArgs | BranchState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BranchState | undefined;
            resourceInputs["database"] = state?.database;
            resourceInputs["gitBranch"] = state?.gitBranch;
            resourceInputs["parentProjectRef"] = state?.parentProjectRef;
            resourceInputs["region"] = state?.region;
        } else {
            const args = argsOrState as BranchArgs | undefined;
            if (args?.gitBranch === undefined && !opts.urn) {
                throw new Error("Missing required property 'gitBranch'");
            }
            if (args?.parentProjectRef === undefined && !opts.urn) {
                throw new Error("Missing required property 'parentProjectRef'");
            }
            resourceInputs["gitBranch"] = args?.gitBranch;
            resourceInputs["parentProjectRef"] = args?.parentProjectRef;
            resourceInputs["region"] = args?.region;
            resourceInputs["database"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Branch.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Branch resources.
 */
export interface BranchState {
    /**
     * Database connection details
     */
    database?: pulumi.Input<inputs.BranchDatabase | undefined>;
    /**
     * Git branch
     */
    gitBranch?: pulumi.Input<string | undefined>;
    /**
     * Parent project ref
     */
    parentProjectRef?: pulumi.Input<string | undefined>;
    /**
     * Database region
     */
    region?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Branch resource.
 */
export interface BranchArgs {
    /**
     * Git branch
     */
    gitBranch: pulumi.Input<string>;
    /**
     * Parent project ref
     */
    parentProjectRef: pulumi.Input<string>;
    /**
     * Database region
     */
    region?: pulumi.Input<string | undefined>;
}
