// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class EdgeFunctionSecrets extends pulumi.CustomResource {
    /**
     * Get an existing EdgeFunctionSecrets resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EdgeFunctionSecretsState, opts?: pulumi.CustomResourceOptions): EdgeFunctionSecrets {
        return new EdgeFunctionSecrets(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'supabase:index/edgeFunctionSecrets:EdgeFunctionSecrets';

    /**
     * Returns true if the given object is an instance of EdgeFunctionSecrets.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EdgeFunctionSecrets {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EdgeFunctionSecrets.__pulumiType;
    }

    /**
     * Project reference ID
     */
    declare public readonly projectRef: pulumi.Output<string>;
    /**
     * Map of secret name to the SHA-256 hex digest of the secret value. Computed by the provider at plan time (when plaintext values are known) and updated after each apply. Used to detect drift when a secret has been changed outside of Terraform: if the digest returned by the API no longer matches the locally computed digest, the provider marks the affected secret value as null so Terraform will plan an update.
     */
    declare public /*out*/ readonly secretDigests: pulumi.Output<{[key: string]: string}>;
    /**
     * Set of secrets for edge functions
     */
    declare public readonly secrets: pulumi.Output<outputs.EdgeFunctionSecretsSecret[]>;

    /**
     * Create a EdgeFunctionSecrets resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EdgeFunctionSecretsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EdgeFunctionSecretsArgs | EdgeFunctionSecretsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EdgeFunctionSecretsState | undefined;
            resourceInputs["projectRef"] = state?.projectRef;
            resourceInputs["secretDigests"] = state?.secretDigests;
            resourceInputs["secrets"] = state?.secrets;
        } else {
            const args = argsOrState as EdgeFunctionSecretsArgs | undefined;
            if (args?.projectRef === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectRef'");
            }
            if (args?.secrets === undefined && !opts.urn) {
                throw new Error("Missing required property 'secrets'");
            }
            resourceInputs["projectRef"] = args?.projectRef;
            resourceInputs["secrets"] = args?.secrets;
            resourceInputs["secretDigests"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EdgeFunctionSecrets.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EdgeFunctionSecrets resources.
 */
export interface EdgeFunctionSecretsState {
    /**
     * Project reference ID
     */
    projectRef?: pulumi.Input<string | undefined>;
    /**
     * Map of secret name to the SHA-256 hex digest of the secret value. Computed by the provider at plan time (when plaintext values are known) and updated after each apply. Used to detect drift when a secret has been changed outside of Terraform: if the digest returned by the API no longer matches the locally computed digest, the provider marks the affected secret value as null so Terraform will plan an update.
     */
    secretDigests?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Set of secrets for edge functions
     */
    secrets?: pulumi.Input<pulumi.Input<inputs.EdgeFunctionSecretsSecret>[] | undefined>;
}

/**
 * The set of arguments for constructing a EdgeFunctionSecrets resource.
 */
export interface EdgeFunctionSecretsArgs {
    /**
     * Project reference ID
     */
    projectRef: pulumi.Input<string>;
    /**
     * Set of secrets for edge functions
     */
    secrets: pulumi.Input<pulumi.Input<inputs.EdgeFunctionSecretsSecret>[]>;
}
