// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EdgeFunction extends pulumi.CustomResource {
    /**
     * Get an existing EdgeFunction resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EdgeFunctionState, opts?: pulumi.CustomResourceOptions): EdgeFunction {
        return new EdgeFunction(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'supabase:index/edgeFunction:EdgeFunction';

    /**
     * Returns true if the given object is an instance of EdgeFunction.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EdgeFunction {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EdgeFunction.__pulumiType;
    }

    /**
     * SHA256 checksum of the deployed function bundle (remote)
     */
    declare public /*out*/ readonly checksum: pulumi.Output<string>;
    /**
     * Timestamp when the function was created
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * Path to the function entrypoint file
     */
    declare public readonly entrypoint: pulumi.Output<string>;
    /**
     * Path to the import map file
     */
    declare public readonly importMap: pulumi.Output<string | undefined>;
    /**
     * SHA256 checksum of local source files before upload
     */
    declare public /*out*/ readonly localChecksum: pulumi.Output<string>;
    /**
     * Name of the function (defaults to slug if not specified)
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Project ref
     */
    declare public readonly projectRef: pulumi.Output<string>;
    /**
     * URL-friendly identifier for the function
     */
    declare public readonly slug: pulumi.Output<string>;
    /**
     * List of glob patterns for static files to include
     */
    declare public readonly staticFiles: pulumi.Output<string[] | undefined>;
    /**
     * Function deployment status
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Timestamp when the function was last updated
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<number>;
    /**
     * Currently deployed function version
     */
    declare public /*out*/ readonly version: pulumi.Output<number>;

    /**
     * Create a EdgeFunction resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EdgeFunctionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EdgeFunctionArgs | EdgeFunctionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EdgeFunctionState | undefined;
            resourceInputs["checksum"] = state?.checksum;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["entrypoint"] = state?.entrypoint;
            resourceInputs["importMap"] = state?.importMap;
            resourceInputs["localChecksum"] = state?.localChecksum;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectRef"] = state?.projectRef;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["staticFiles"] = state?.staticFiles;
            resourceInputs["status"] = state?.status;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as EdgeFunctionArgs | undefined;
            if (args?.entrypoint === undefined && !opts.urn) {
                throw new Error("Missing required property 'entrypoint'");
            }
            if (args?.projectRef === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectRef'");
            }
            if (args?.slug === undefined && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            resourceInputs["entrypoint"] = args?.entrypoint;
            resourceInputs["importMap"] = args?.importMap;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectRef"] = args?.projectRef;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["staticFiles"] = args?.staticFiles;
            resourceInputs["checksum"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["localChecksum"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EdgeFunction.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EdgeFunction resources.
 */
export interface EdgeFunctionState {
    /**
     * SHA256 checksum of the deployed function bundle (remote)
     */
    checksum?: pulumi.Input<string | undefined>;
    /**
     * Timestamp when the function was created
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * Path to the function entrypoint file
     */
    entrypoint?: pulumi.Input<string | undefined>;
    /**
     * Path to the import map file
     */
    importMap?: pulumi.Input<string | undefined>;
    /**
     * SHA256 checksum of local source files before upload
     */
    localChecksum?: pulumi.Input<string | undefined>;
    /**
     * Name of the function (defaults to slug if not specified)
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Project ref
     */
    projectRef?: pulumi.Input<string | undefined>;
    /**
     * URL-friendly identifier for the function
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * List of glob patterns for static files to include
     */
    staticFiles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Function deployment status
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Timestamp when the function was last updated
     */
    updatedAt?: pulumi.Input<number | undefined>;
    /**
     * Currently deployed function version
     */
    version?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a EdgeFunction resource.
 */
export interface EdgeFunctionArgs {
    /**
     * Path to the function entrypoint file
     */
    entrypoint: pulumi.Input<string>;
    /**
     * Path to the import map file
     */
    importMap?: pulumi.Input<string | undefined>;
    /**
     * Name of the function (defaults to slug if not specified)
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Project ref
     */
    projectRef: pulumi.Input<string>;
    /**
     * URL-friendly identifier for the function
     */
    slug: pulumi.Input<string>;
    /**
     * List of glob patterns for static files to include
     */
    staticFiles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
