// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getApikeys(args: GetApikeysArgs, opts?: pulumi.InvokeOptions): Promise<GetApikeysResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("supabase:index/getApikeys:getApikeys", {
        "projectRef": args.projectRef,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApikeys.
 */
export interface GetApikeysArgs {
    projectRef: string;
}

/**
 * A collection of values returned by getApikeys.
 */
export interface GetApikeysResult {
    readonly anonKey: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly projectRef: string;
    readonly publishableKey: string;
    readonly secretKeys: outputs.GetApikeysSecretKey[];
    readonly serviceRoleKey: string;
}
export function getApikeysOutput(args: GetApikeysOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetApikeysResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("supabase:index/getApikeys:getApikeys", {
        "projectRef": args.projectRef,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApikeys.
 */
export interface GetApikeysOutputArgs {
    projectRef: pulumi.Input<string>;
}
