// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBranch(args: GetBranchArgs, opts?: pulumi.InvokeOptions): Promise<GetBranchResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("supabase:index/getBranch:getBranch", {
        "parentProjectRef": args.parentProjectRef,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBranch.
 */
export interface GetBranchArgs {
    parentProjectRef: string;
}

/**
 * A collection of values returned by getBranch.
 */
export interface GetBranchResult {
    readonly branches: outputs.GetBranchBranch[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly parentProjectRef: string;
}
export function getBranchOutput(args: GetBranchOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBranchResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("supabase:index/getBranch:getBranch", {
        "parentProjectRef": args.parentProjectRef,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBranch.
 */
export interface GetBranchOutputArgs {
    parentProjectRef: pulumi.Input<string>;
}
