// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNetworkBans(args: GetNetworkBansArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkBansResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("supabase:index/getNetworkBans:getNetworkBans", {
        "projectRef": args.projectRef,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkBans.
 */
export interface GetNetworkBansArgs {
    projectRef: string;
}

/**
 * A collection of values returned by getNetworkBans.
 */
export interface GetNetworkBansResult {
    readonly bannedIpv4Addresses: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly projectRef: string;
}
export function getNetworkBansOutput(args: GetNetworkBansOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNetworkBansResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("supabase:index/getNetworkBans:getNetworkBans", {
        "projectRef": args.projectRef,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkBans.
 */
export interface GetNetworkBansOutputArgs {
    projectRef: pulumi.Input<string>;
}
