// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPooler(args: GetPoolerArgs, opts?: pulumi.InvokeOptions): Promise<GetPoolerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("supabase:index/getPooler:getPooler", {
        "projectRef": args.projectRef,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPooler.
 */
export interface GetPoolerArgs {
    projectRef: string;
}

/**
 * A collection of values returned by getPooler.
 */
export interface GetPoolerResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly projectRef: string;
    readonly url: {[key: string]: string};
}
export function getPoolerOutput(args: GetPoolerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPoolerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("supabase:index/getPooler:getPooler", {
        "projectRef": args.projectRef,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPooler.
 */
export interface GetPoolerOutputArgs {
    projectRef: pulumi.Input<string>;
}
