// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApikeyArgs, ApikeyState } from "./apikey";
export type Apikey = import("./apikey").Apikey;
export const Apikey: typeof import("./apikey").Apikey = null as any;
utilities.lazyLoad(exports, ["Apikey"], () => require("./apikey"));

export { BranchArgs, BranchState } from "./branch";
export type Branch = import("./branch").Branch;
export const Branch: typeof import("./branch").Branch = null as any;
utilities.lazyLoad(exports, ["Branch"], () => require("./branch"));

export { EdgeFunctionArgs, EdgeFunctionState } from "./edgeFunction";
export type EdgeFunction = import("./edgeFunction").EdgeFunction;
export const EdgeFunction: typeof import("./edgeFunction").EdgeFunction = null as any;
utilities.lazyLoad(exports, ["EdgeFunction"], () => require("./edgeFunction"));

export { EdgeFunctionSecretsArgs, EdgeFunctionSecretsState } from "./edgeFunctionSecrets";
export type EdgeFunctionSecrets = import("./edgeFunctionSecrets").EdgeFunctionSecrets;
export const EdgeFunctionSecrets: typeof import("./edgeFunctionSecrets").EdgeFunctionSecrets = null as any;
utilities.lazyLoad(exports, ["EdgeFunctionSecrets"], () => require("./edgeFunctionSecrets"));

export { GetApikeysArgs, GetApikeysResult, GetApikeysOutputArgs } from "./getApikeys";
export const getApikeys: typeof import("./getApikeys").getApikeys = null as any;
export const getApikeysOutput: typeof import("./getApikeys").getApikeysOutput = null as any;
utilities.lazyLoad(exports, ["getApikeys","getApikeysOutput"], () => require("./getApikeys"));

export { GetBranchArgs, GetBranchResult, GetBranchOutputArgs } from "./getBranch";
export const getBranch: typeof import("./getBranch").getBranch = null as any;
export const getBranchOutput: typeof import("./getBranch").getBranchOutput = null as any;
utilities.lazyLoad(exports, ["getBranch","getBranchOutput"], () => require("./getBranch"));

export { GetNetworkBansArgs, GetNetworkBansResult, GetNetworkBansOutputArgs } from "./getNetworkBans";
export const getNetworkBans: typeof import("./getNetworkBans").getNetworkBans = null as any;
export const getNetworkBansOutput: typeof import("./getNetworkBans").getNetworkBansOutput = null as any;
utilities.lazyLoad(exports, ["getNetworkBans","getNetworkBansOutput"], () => require("./getNetworkBans"));

export { GetPoolerArgs, GetPoolerResult, GetPoolerOutputArgs } from "./getPooler";
export const getPooler: typeof import("./getPooler").getPooler = null as any;
export const getPoolerOutput: typeof import("./getPooler").getPoolerOutput = null as any;
utilities.lazyLoad(exports, ["getPooler","getPoolerOutput"], () => require("./getPooler"));

export { ProjectArgs, ProjectState } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export * from "./provider";
import { Provider } from "./provider";

export { SettingsArgs, SettingsState } from "./settings";
export type Settings = import("./settings").Settings;
export const Settings: typeof import("./settings").Settings = null as any;
utilities.lazyLoad(exports, ["Settings"], () => require("./settings"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "supabase:index/apikey:Apikey":
                return new Apikey(name, <any>undefined, { urn })
            case "supabase:index/branch:Branch":
                return new Branch(name, <any>undefined, { urn })
            case "supabase:index/edgeFunction:EdgeFunction":
                return new EdgeFunction(name, <any>undefined, { urn })
            case "supabase:index/edgeFunctionSecrets:EdgeFunctionSecrets":
                return new EdgeFunctionSecrets(name, <any>undefined, { urn })
            case "supabase:index/project:Project":
                return new Project(name, <any>undefined, { urn })
            case "supabase:index/settings:Settings":
                return new Settings(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("supabase", "index/apikey", _module)
pulumi.runtime.registerResourceModule("supabase", "index/branch", _module)
pulumi.runtime.registerResourceModule("supabase", "index/edgeFunction", _module)
pulumi.runtime.registerResourceModule("supabase", "index/edgeFunctionSecrets", _module)
pulumi.runtime.registerResourceModule("supabase", "index/project", _module)
pulumi.runtime.registerResourceModule("supabase", "index/settings", _module)
pulumi.runtime.registerResourcePackage("supabase", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:supabase") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
