// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectState, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'supabase:index/project:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * Password for the project database
     */
    declare public readonly databasePassword: pulumi.Output<string>;
    /**
     * Desired instance size of the project
     */
    declare public readonly instanceSize: pulumi.Output<string>;
    /**
     * Controls whether <span pulumi-lang-nodejs="`anon`" pulumi-lang-dotnet="`Anon`" pulumi-lang-go="`anon`" pulumi-lang-python="`anon`" pulumi-lang-yaml="`anon`" pulumi-lang-java="`anon`" pulumi-lang-hcl="`anon`">`anon`</span> and <span pulumi-lang-nodejs="`serviceRole`" pulumi-lang-dotnet="`ServiceRole`" pulumi-lang-go="`serviceRole`" pulumi-lang-python="`service_role`" pulumi-lang-yaml="`serviceRole`" pulumi-lang-java="`serviceRole`" pulumi-lang-hcl="`service_role`">`serviceRole`</span> JWT-based api keys should be enabled. Please note: these keys are no longer recommended ([more information here](https://supabase.com/docs/guides/api/api-keys#why-are-anon-and-servicerole-jwt-based-keys-no-longer-recommended)).
     *
     * @deprecated Deprecated
     */
    declare public readonly legacyApiKeysEnabled: pulumi.Output<boolean>;
    /**
     * Name of the project
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Organization slug (found in the Supabase dashboard URL or organization settings)
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * Region where the project is located
     */
    declare public readonly region: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.ProjectTimeouts | undefined>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectArgs | ProjectState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectState | undefined;
            resourceInputs["databasePassword"] = state?.databasePassword;
            resourceInputs["instanceSize"] = state?.instanceSize;
            resourceInputs["legacyApiKeysEnabled"] = state?.legacyApiKeysEnabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["region"] = state?.region;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as ProjectArgs | undefined;
            if (args?.databasePassword === undefined && !opts.urn) {
                throw new Error("Missing required property 'databasePassword'");
            }
            if (args?.organizationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["databasePassword"] = args?.databasePassword ? pulumi.secret(args.databasePassword) : undefined;
            resourceInputs["instanceSize"] = args?.instanceSize;
            resourceInputs["legacyApiKeysEnabled"] = args?.legacyApiKeysEnabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["region"] = args?.region;
            resourceInputs["timeouts"] = args?.timeouts;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["databasePassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Project.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Project resources.
 */
export interface ProjectState {
    /**
     * Password for the project database
     */
    databasePassword?: pulumi.Input<string | undefined>;
    /**
     * Desired instance size of the project
     */
    instanceSize?: pulumi.Input<string | undefined>;
    /**
     * Controls whether <span pulumi-lang-nodejs="`anon`" pulumi-lang-dotnet="`Anon`" pulumi-lang-go="`anon`" pulumi-lang-python="`anon`" pulumi-lang-yaml="`anon`" pulumi-lang-java="`anon`" pulumi-lang-hcl="`anon`">`anon`</span> and <span pulumi-lang-nodejs="`serviceRole`" pulumi-lang-dotnet="`ServiceRole`" pulumi-lang-go="`serviceRole`" pulumi-lang-python="`service_role`" pulumi-lang-yaml="`serviceRole`" pulumi-lang-java="`serviceRole`" pulumi-lang-hcl="`service_role`">`serviceRole`</span> JWT-based api keys should be enabled. Please note: these keys are no longer recommended ([more information here](https://supabase.com/docs/guides/api/api-keys#why-are-anon-and-servicerole-jwt-based-keys-no-longer-recommended)).
     *
     * @deprecated Deprecated
     */
    legacyApiKeysEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the project
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Organization slug (found in the Supabase dashboard URL or organization settings)
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * Region where the project is located
     */
    region?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.ProjectTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * Password for the project database
     */
    databasePassword: pulumi.Input<string>;
    /**
     * Desired instance size of the project
     */
    instanceSize?: pulumi.Input<string | undefined>;
    /**
     * Controls whether <span pulumi-lang-nodejs="`anon`" pulumi-lang-dotnet="`Anon`" pulumi-lang-go="`anon`" pulumi-lang-python="`anon`" pulumi-lang-yaml="`anon`" pulumi-lang-java="`anon`" pulumi-lang-hcl="`anon`">`anon`</span> and <span pulumi-lang-nodejs="`serviceRole`" pulumi-lang-dotnet="`ServiceRole`" pulumi-lang-go="`serviceRole`" pulumi-lang-python="`service_role`" pulumi-lang-yaml="`serviceRole`" pulumi-lang-java="`serviceRole`" pulumi-lang-hcl="`service_role`">`serviceRole`</span> JWT-based api keys should be enabled. Please note: these keys are no longer recommended ([more information here](https://supabase.com/docs/guides/api/api-keys#why-are-anon-and-servicerole-jwt-based-keys-no-longer-recommended)).
     *
     * @deprecated Deprecated
     */
    legacyApiKeysEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the project
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Organization slug (found in the Supabase dashboard URL or organization settings)
     */
    organizationId: pulumi.Input<string>;
    /**
     * Region where the project is located
     */
    region: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.ProjectTimeouts | undefined>;
}
