// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Settings extends pulumi.CustomResource {
    /**
     * Get an existing Settings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SettingsState, opts?: pulumi.CustomResourceOptions): Settings {
        return new Settings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'supabase:index/settings:Settings';

    /**
     * Returns true if the given object is an instance of Settings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Settings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Settings.__pulumiType;
    }

    /**
     * API settings as [serialised JSON](https://api.supabase.com/api/v1#/services/updatePostgRESTConfig)
     */
    declare public readonly api: pulumi.Output<string | undefined>;
    /**
     * Auth settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateV1AuthConfig)
     */
    declare public readonly auth: pulumi.Output<string | undefined>;
    /**
     * Database settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateConfig)
     */
    declare public readonly database: pulumi.Output<string | undefined>;
    /**
     * Network settings as serialised JSON
     */
    declare public readonly network: pulumi.Output<string | undefined>;
    /**
     * Pooler settings as serialised JSON
     */
    declare public readonly pooler: pulumi.Output<string | undefined>;
    /**
     * Project reference ID
     */
    declare public readonly projectRef: pulumi.Output<string>;
    /**
     * Storage settings as serialised JSON
     */
    declare public readonly storage: pulumi.Output<string | undefined>;
    declare public readonly timeouts: pulumi.Output<outputs.SettingsTimeouts | undefined>;

    /**
     * Create a Settings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SettingsArgs | SettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SettingsState | undefined;
            resourceInputs["api"] = state?.api;
            resourceInputs["auth"] = state?.auth;
            resourceInputs["database"] = state?.database;
            resourceInputs["network"] = state?.network;
            resourceInputs["pooler"] = state?.pooler;
            resourceInputs["projectRef"] = state?.projectRef;
            resourceInputs["storage"] = state?.storage;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as SettingsArgs | undefined;
            if (args?.projectRef === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectRef'");
            }
            resourceInputs["api"] = args?.api;
            resourceInputs["auth"] = args?.auth;
            resourceInputs["database"] = args?.database;
            resourceInputs["network"] = args?.network;
            resourceInputs["pooler"] = args?.pooler;
            resourceInputs["projectRef"] = args?.projectRef;
            resourceInputs["storage"] = args?.storage;
            resourceInputs["timeouts"] = args?.timeouts;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Settings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Settings resources.
 */
export interface SettingsState {
    /**
     * API settings as [serialised JSON](https://api.supabase.com/api/v1#/services/updatePostgRESTConfig)
     */
    api?: pulumi.Input<string | undefined>;
    /**
     * Auth settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateV1AuthConfig)
     */
    auth?: pulumi.Input<string | undefined>;
    /**
     * Database settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateConfig)
     */
    database?: pulumi.Input<string | undefined>;
    /**
     * Network settings as serialised JSON
     */
    network?: pulumi.Input<string | undefined>;
    /**
     * Pooler settings as serialised JSON
     */
    pooler?: pulumi.Input<string | undefined>;
    /**
     * Project reference ID
     */
    projectRef?: pulumi.Input<string | undefined>;
    /**
     * Storage settings as serialised JSON
     */
    storage?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.SettingsTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a Settings resource.
 */
export interface SettingsArgs {
    /**
     * API settings as [serialised JSON](https://api.supabase.com/api/v1#/services/updatePostgRESTConfig)
     */
    api?: pulumi.Input<string | undefined>;
    /**
     * Auth settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateV1AuthConfig)
     */
    auth?: pulumi.Input<string | undefined>;
    /**
     * Database settings as [serialised JSON](https://api.supabase.com/api/v1#/projects%20config/updateConfig)
     */
    database?: pulumi.Input<string | undefined>;
    /**
     * Network settings as serialised JSON
     */
    network?: pulumi.Input<string | undefined>;
    /**
     * Pooler settings as serialised JSON
     */
    pooler?: pulumi.Input<string | undefined>;
    /**
     * Project reference ID
     */
    projectRef: pulumi.Input<string>;
    /**
     * Storage settings as serialised JSON
     */
    storage?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.SettingsTimeouts | undefined>;
}
