// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ApikeySecretJwtTemplate {
    /**
     * Role of the secret JWT template
     */
    role?: pulumi.Input<string | undefined>;
}

export interface BranchDatabase {
    /**
     * Host
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * Branch project ref
     */
    id?: pulumi.Input<string | undefined>;
    /**
     * JWT secret
     */
    jwtSecret?: pulumi.Input<string | undefined>;
    /**
     * Password
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * Port
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * Status
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * User
     */
    user?: pulumi.Input<string | undefined>;
    /**
     * Postgres version
     */
    version?: pulumi.Input<string | undefined>;
}

export interface EdgeFunctionSecretsSecret {
    /**
     * Name of the secret. Must not start with the `SUPABASE_` prefix — such names are reserved internally by Supabase, cannot be created, updated, or deleted via the API, and are automatically filtered out from reads and imports.
     */
    name: pulumi.Input<string>;
    /**
     * The plaintext secret value. Stored in Terraform state when managed by Terraform. After an import this field will be <span pulumi-lang-nodejs="`null`" pulumi-lang-dotnet="`Null`" pulumi-lang-go="`null`" pulumi-lang-python="`null`" pulumi-lang-yaml="`null`" pulumi-lang-java="`null`" pulumi-lang-hcl="`null`">`null`</span> because the Supabase API only returns SHA-256 digests — see the Import section below.
     */
    value: pulumi.Input<string>;
}

export interface ProjectTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: pulumi.Input<string | undefined>;
}

export interface SettingsTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: pulumi.Input<string | undefined>;
}
