import {
  AlertTriangle,
  Bell,
  Bike,
  Car,
  CalendarCheck,
  CalendarClock,
  ClipboardCheck,
  Folder,
  Handshake,
  UtensilsCrossed,
  Inbox,
  Languages,
  LayoutDashboard,
  LifeBuoy,
  ListTree,
  MapPin,
  Package,
  Paintbrush,
  Settings as SettingsIcon,
  Shield,
  Smartphone,
  ToggleLeft,
  User,
  UserCheck,
  Users,
  Wallet,
  Cloud,
  Download,
  FormInput,
  Gauge,
  ScrollText,
  Radar,
  Satellite,
  Timer,
  Trash2,
  type LucideIcon,
} from "lucide-react";
import type { Permission } from "@/lib/auth/permissions";

export type MenuRegistryItem = {
  id: string;
  defaultLabel: string;
  defaultIcon: string;
  href: string;
  defaultGroup: string;
  defaultOrder: number;
  permission?: Permission;
  superAdminOnly?: boolean;
  footer?: boolean;
};

export const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Users,
  Package,
  Bike,
  Car,
  CalendarCheck,
  CalendarClock,
  ClipboardCheck,
  Inbox,
  AlertTriangle,
  Wallet,
  Bell,
  LifeBuoy,
  Settings: SettingsIcon,
  Languages,
  ListTree,
  Folder,
  Handshake,
  UtensilsCrossed,
  MapPin,
  Paintbrush,
  Shield,
  Smartphone,
  ToggleLeft,
  User,
  UserCheck,
  Cloud,
  ScrollText,
  Radar,
  Satellite,
  Timer,
  Trash2,
  Download,
  FormInput,
  Gauge,
};

export const ICON_NAMES = Object.keys(ICON_MAP);

export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? LayoutDashboard;
}

export const DEFAULT_GROUPS = [
  "Overview",
  "Operations",
  "Settings",
  "WIP",
  "Unorganised",
];

export const DEFAULT_GROUP_META: Record<
  string,
  { icon: string; displayMode?: "inline" | "panel" }
> = {
  Overview: { icon: "Folder" },
  Operations: { icon: "Folder", displayMode: "panel" },
  Settings: { icon: "Settings", displayMode: "inline" },
  WIP: { icon: "AlertTriangle", displayMode: "panel" },
  Unorganised: { icon: "Folder" },
};

export const MENU_REGISTRY: MenuRegistryItem[] = [
  {
    id: "dashboard",
    defaultLabel: "Dashboard",
    defaultIcon: "LayoutDashboard",
    href: "/dashboard",
    defaultGroup: "Overview",
    defaultOrder: 0,
    permission: "dashboard.view",
  },
  {
    id: "drivers",
    defaultLabel: "Drivers",
    defaultIcon: "Users",
    href: "/drivers",
    defaultGroup: "Operations",
    defaultOrder: 0,
    permission: "drivers.view",
  },
  {
    id: "driver-groups",
    defaultLabel: "Driver groups",
    defaultIcon: "UserCheck",
    href: "/drivers/groups",
    defaultGroup: "Operations",
    defaultOrder: 0.5,
    permission: "driver_groups.view",
  },
  {
    id: "live-tracking",
    defaultLabel: "Live tracking",
    defaultIcon: "Radar",
    href: "/live-tracking",
    defaultGroup: "Operations",
    defaultOrder: 1,
    permission: "drivers.view",
  },
  {
    id: "live-tracking-v2",
    defaultLabel: "Live tracking V2",
    defaultIcon: "Satellite",
    href: "/live-tracking-v2",
    defaultGroup: "Operations",
    defaultOrder: 1.5,
    permission: "drivers.view",
  },
  {
    id: "partners",
    defaultLabel: "Partners",
    defaultIcon: "Handshake",
    href: "/partners",
    defaultGroup: "Operations",
    defaultOrder: 2,
    permission: "partners.view",
  },
  {
    id: "assets",
    defaultLabel: "Assets",
    defaultIcon: "Package",
    href: "/assets",
    defaultGroup: "Operations",
    defaultOrder: 9,
    permission: "assets.view",
  },
  {
    id: "restaurants",
    defaultLabel: "Restaurants",
    defaultIcon: "UtensilsCrossed",
    href: "/restaurants",
    defaultGroup: "Operations",
    defaultOrder: 3,
    permission: "restaurants.view",
  },
  {
    id: "deliveries",
    defaultLabel: "Live Deliveries",
    defaultIcon: "Package",
    href: "/deliveries",
    defaultGroup: "Operations",
    defaultOrder: 4,
    permission: "deliveries.view",
  },
  {
    id: "dpd-verification",
    defaultLabel: "DPD Verification",
    defaultIcon: "ClipboardCheck",
    href: "/dpd-verification",
    defaultGroup: "Operations",
    defaultOrder: 5,
    permission: "verifications.view",
  },
  {
    id: "vehicles",
    defaultLabel: "Vehicles",
    defaultIcon: "Bike",
    href: "/vehicles",
    defaultGroup: "WIP",
    defaultOrder: 4,
    permission: "vehicles.view",
  },
  {
    id: "attendance",
    defaultLabel: "Attendance",
    defaultIcon: "ClipboardCheck",
    href: "/attendance",
    defaultGroup: "Operations",
    defaultOrder: 7,
    permission: "attendance.view",
  },
  {
    id: "performance",
    defaultLabel: "Performance",
    defaultIcon: "Gauge",
    href: "/performance",
    defaultGroup: "Operations",
    defaultOrder: 8,
    permission: "performance.view",
  },
  {
    id: "requests",
    defaultLabel: "Request & Complaint",
    defaultIcon: "Inbox",
    href: "/requests",
    defaultGroup: "WIP",
    defaultOrder: 6,
    permission: "requests.view",
  },
  {
    id: "visit-bookings",
    defaultLabel: "Visit Bookings",
    defaultIcon: "CalendarCheck",
    href: "/visit-bookings",
    defaultGroup: "WIP",
    defaultOrder: 6.5,
    permission: "visits.view",
  },
  {
    id: "wrong-actions",
    defaultLabel: "Wrong Actions",
    defaultIcon: "AlertTriangle",
    href: "/wrong-actions",
    defaultGroup: "WIP",
    defaultOrder: 7,
    permission: "wrong_actions.view",
  },
  {
    id: "earnings",
    defaultLabel: "Earnings & Incentives",
    defaultIcon: "Wallet",
    href: "/earnings",
    defaultGroup: "WIP",
    defaultOrder: 8,
    permission: "earnings.view",
  },
  {
    id: "delivery-rules",
    defaultLabel: "Delivery rules",
    defaultIcon: "ListTree",
    href: "/delivery-rules",
    defaultGroup: "Operations",
    defaultOrder: 9,
    permission: "earnings.view",
  },
  {
    id: "incentive-rules",
    defaultLabel: "Incentive rules",
    defaultIcon: "Wallet",
    href: "/incentive-rules",
    defaultGroup: "Operations",
    defaultOrder: 10,
    permission: "earnings.view",
  },
  {
    id: "earnings-calculation",
    defaultLabel: "Earnings calculation",
    defaultIcon: "ToggleLeft",
    href: "/earnings-calculation",
    defaultGroup: "Operations",
    defaultOrder: 11,
    permission: "earnings.view",
  },
  {
    id: "payouts",
    defaultLabel: "Payouts",
    defaultIcon: "Wallet",
    href: "/payouts",
    defaultGroup: "Operations",
    defaultOrder: 12,
    permission: "earnings.view",
  },
  {
    id: "notifications",
    defaultLabel: "Notifications",
    defaultIcon: "Bell",
    href: "/notifications",
    defaultGroup: "Operations",
    defaultOrder: 8,
    permission: "notifications.view",
  },
  {
    id: "support",
    defaultLabel: "Support",
    defaultIcon: "LifeBuoy",
    href: "/support",
    defaultGroup: "WIP",
    defaultOrder: 10,
    permission: "support.view",
  },
  {
    id: "profile",
    defaultLabel: "Profile",
    defaultIcon: "User",
    href: "/settings",
    defaultGroup: "Settings",
    defaultOrder: 0,
    permission: "settings.view",
  },
  {
    id: "branding",
    defaultLabel: "Branding",
    defaultIcon: "Paintbrush",
    href: "/settings/branding",
    defaultGroup: "Settings",
    defaultOrder: 1,
    permission: "settings.manage",
  },
  {
    id: "driver-app",
    defaultLabel: "Driver App",
    defaultIcon: "Smartphone",
    href: "/settings/app",
    defaultGroup: "Settings",
    defaultOrder: 2,
    permission: "settings.manage",
  },
  {
    id: "vehicle-types",
    defaultLabel: "Vehicle types",
    defaultIcon: "Car",
    href: "/settings/vehicle-types",
    defaultGroup: "Settings",
    defaultOrder: 2.5,
    permission: "vehicles.manage",
  },
  {
    id: "attendance-settings",
    defaultLabel: "Attendance thresholds",
    defaultIcon: "ClipboardCheck",
    href: "/settings/attendance",
    defaultGroup: "Settings",
    defaultOrder: 3,
    permission: "attendance.manage",
  },
  {
    id: "driver-fields",
    defaultLabel: "Driver custom fields",
    defaultIcon: "FormInput",
    href: "/settings/driver-fields",
    defaultGroup: "Settings",
    defaultOrder: 3,
    permission: "drivers.manage",
  },
  {
    id: "storage",
    defaultLabel: "Cloudflare R2",
    defaultIcon: "Cloud",
    href: "/settings/storage",
    defaultGroup: "Settings",
    defaultOrder: 3,
    superAdminOnly: true,
  },
  {
    id: "roles",
    defaultLabel: "Roles & Permissions",
    defaultIcon: "Shield",
    href: "/settings/roles",
    defaultGroup: "Settings",
    defaultOrder: 4,
    superAdminOnly: true,
  },
  {
    id: "access-requests",
    defaultLabel: "Access Requests",
    defaultIcon: "UserCheck",
    href: "/settings/access-requests",
    defaultGroup: "Settings",
    defaultOrder: 5,
    superAdminOnly: true,
  },
  {
    id: "maintenance",
    defaultLabel: "Maintenance",
    defaultIcon: "ToggleLeft",
    href: "/settings/maintenance",
    defaultGroup: "Settings",
    defaultOrder: 6,
    superAdminOnly: true,
  },
  {
    id: "data-cleanup",
    defaultLabel: "Data cleanup",
    defaultIcon: "Trash2",
    href: "/settings/data-cleanup",
    defaultGroup: "Settings",
    defaultOrder: 6.5,
    permission: "data.cleanup",
    superAdminOnly: true,
  },
  {
    id: "menu-editor",
    defaultLabel: "Menu Editor",
    defaultIcon: "ListTree",
    href: "/settings/menu-editor",
    defaultGroup: "Settings",
    defaultOrder: 7,
    superAdminOnly: true,
  },
  {
    id: "languages",
    defaultLabel: "Languages",
    defaultIcon: "Languages",
    href: "/settings/languages",
    defaultGroup: "Settings",
    defaultOrder: 8,
    superAdminOnly: true,
  },
  {
    id: "activity-logs",
    defaultLabel: "Activity Logs",
    defaultIcon: "ScrollText",
    href: "/settings/logs",
    defaultGroup: "Settings",
    defaultOrder: 9,
    permission: "audit.view",
  },
  {
    id: "document-expiry",
    defaultLabel: "Document expiry",
    defaultIcon: "CalendarClock",
    href: "/document-expiry",
    defaultGroup: "Operations",
    defaultOrder: 6.5,
    permission: "documents.view",
  },
  {
    id: "zones",
    defaultLabel: "Zones",
    defaultIcon: "MapPin",
    href: "/zones",
    defaultGroup: "Operations",
    defaultOrder: 6,
    permission: "zones.view",
  },
];

/** Map menu item id → next-intl nav key (without `nav.` prefix). */
export const APP_NAV_KEY_BY_ID: Record<string, string> = {
  dashboard: "dashboard",
  drivers: "drivers",
  "driver-groups": "driverGroups",
  "live-tracking": "liveTracking",
  "live-tracking-v2": "liveTrackingV2",
  partners: "partners",
  assets: "assets",
  restaurants: "restaurants",
  deliveries: "deliveries",
  "dpd-verification": "dpdVerification",
  vehicles: "vehicles",
  attendance: "attendance",
  performance: "performance",
  "attendance-settings": "attendanceSettings",
  requests: "requests",
  "visit-bookings": "visitBookings",
  "wrong-actions": "wrongActions",
  earnings: "earnings",
  "delivery-rules": "deliveryRules",
  "incentive-rules": "incentiveRules",
  "earnings-calculation": "earningsCalculation",
  payouts: "payouts",
  notifications: "notifications",
  support: "support",
  profile: "profile",
  branding: "branding",
  "driver-app": "driverApp",
  storage: "storage",
  roles: "roles",
  "access-requests": "accessRequests",
  maintenance: "maintenance",
  "data-cleanup": "dataCleanup",
  "menu-editor": "menuEditor",
  languages: "languages",
  "activity-logs": "activityLogs",
  "document-expiry": "documentExpiry",
  zones: "zones",
};
