-- Make the autonomous failure audit actually write.
--
-- 20260908100000 shipped log_driver_operation_autonomous behind a Vault secret
-- an operator was meant to create by hand, pasting the project database password
-- into a DSN. Nobody did, so driver_ops_audit_health() has reported
-- secret_missing ever since and every Class B failure - active_pickup_exists,
-- delivery_out_of_range, duplicate_order_id, shift_required - has been rolling
-- its audit row back along with the caller, which is the exact hole the emitter
-- was written to close.
--
-- Here the password is generated by gen_random_bytes and consumed inside the
-- same DO block: never selected, never raised, never returned. The only copy
-- that outlives the statement is the one Vault encrypts. That also detaches the
-- audit path from the project password, whose rotation would otherwise silently
-- stop recording delivery failures.
--
-- The auditor cannot touch the trail it feeds. It gets no table privileges, no
-- USAGE on public, and a single EXECUTE on the receiver below - which is
-- SECURITY DEFINER, owned by postgres, and lives in its own schema precisely so
-- that granting the auditor access to it does not also expose every other
-- function in public. A leaked DSN can append one failure row and nothing else:
-- it cannot read, alter or delete the history that holds drivers to account.

-- ---------------------------------------------------------------------------
-- Receiver: the only thing the auditor role is allowed to reach
-- ---------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS driver_ops_audit AUTHORIZATION postgres;
REVOKE ALL ON SCHEMA driver_ops_audit FROM PUBLIC;

COMMENT ON SCHEMA driver_ops_audit IS
  'Loopback surface for the autonomous driver failure audit. Exists so driver_ops_auditor needs no USAGE on public.';

-- search_path is empty and every object is schema-qualified. Naming schemas
-- would be weaker: this executes as postgres on a connection the auditor role
-- controls, so nothing it resolves may depend on the caller search_path.
CREATE OR REPLACE FUNCTION driver_ops_audit.log_driver_operation_remote(
  p_driver_id     uuid,
  p_category      text,
  p_operation_key text,
  p_source_name   text,
  p_error_code    text,
  p_context       jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_driver_id IS NULL THEN
    RETURN;
  END IF;

  -- Selected out of drivers so device_id / app_version_code are stamped exactly
  -- as the in-transaction emitter stamps them, and so a driver row that no
  -- longer exists writes nothing instead of failing the foreign key.
  INSERT INTO public.driver_operation_events (
    driver_id, category, operation_key, source, source_name,
    success, error_code, context, device_id, app_version_code
  )
  SELECT
    d.id, p_category, p_operation_key, 'rpc', p_source_name,
    false, p_error_code, COALESCE(p_context, '{}'::jsonb),
    d.active_device_id, d.current_app_version_code
  FROM public.drivers d
  WHERE d.id = p_driver_id;
EXCEPTION WHEN others THEN
  -- Best effort, like both emitters. It runs on a separate connection after the
  -- caller has already aborted, so it can neither reach nor change the error the
  -- driver app receives.
  RETURN;
END;
$$;

ALTER FUNCTION driver_ops_audit.log_driver_operation_remote(uuid, text, text, text, text, jsonb)
  OWNER TO postgres;

REVOKE ALL ON FUNCTION driver_ops_audit.log_driver_operation_remote(uuid, text, text, text, text, jsonb)
  FROM PUBLIC, anon, authenticated, service_role;

COMMENT ON FUNCTION driver_ops_audit.log_driver_operation_remote(uuid, text, text, text, text, jsonb) IS
  'Loopback entry point for the autonomous driver failure audit. EXECUTE is granted to driver_ops_auditor only.';

-- ---------------------------------------------------------------------------
-- Auditor role + Vault DSN
-- ---------------------------------------------------------------------------

DO $provision$
DECLARE
  -- hex, so the password never needs percent-encoding inside the DSN
  v_password  text := encode(extensions.gen_random_bytes(24), 'hex');
  v_dsn       text;
  v_secret_id uuid;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'driver_ops_auditor') THEN
    EXECUTE format('ALTER ROLE driver_ops_auditor WITH LOGIN PASSWORD %L', v_password);
  ELSE
    EXECUTE format('CREATE ROLE driver_ops_auditor WITH LOGIN PASSWORD %L', v_password);
  END IF;

  -- Everything a failure-audit writer has no use for. The connection limit keeps
  -- a burst of failures from eating into the pool the drivers depend on.
  -- NOSUPERUSER / NOREPLICATION / NOBYPASSRLS are deliberately absent: on managed
  -- Postgres the migration role is not a superuser, and touching those three
  -- attributes at all - even to clear them - requires one. They are the defaults
  -- for a freshly created role, and the assertions below prove they held.
  ALTER ROLE driver_ops_auditor
    NOCREATEDB NOCREATEROLE INHERIT
    CONNECTION LIMIT 5;

  IF EXISTS (
    SELECT 1 FROM pg_roles
    WHERE rolname = 'driver_ops_auditor'
      AND (rolsuper OR rolbypassrls OR rolreplication OR rolcreaterole OR rolcreatedb)
  ) THEN
    RAISE EXCEPTION 'driver_ops_auditor holds an elevated attribute; refusing to hand it a login DSN';
  END IF;

  EXECUTE format('GRANT CONNECT ON DATABASE %I TO driver_ops_auditor', current_database());

  -- dblink_exec blocks the RPC that is trying to report its own failure, so both
  -- of these are user-facing: they bound how long a driver waits for an error
  -- message when the audit path is degraded rather than down. connect_timeout in
  -- the DSN below covers the third case, an unreachable host.
  ALTER ROLE driver_ops_auditor SET statement_timeout = '5s';
  ALTER ROLE driver_ops_auditor SET lock_timeout = '2s';
  ALTER ROLE driver_ops_auditor SET idle_in_transaction_session_timeout = '10s';

  -- No REVOKE on schema public here, because it would be theatre: USAGE on public
  -- is granted to the PUBLIC pseudo-role, so every login role holds it and no
  -- per-role REVOKE can take it away. What that leaves reachable is the set of
  -- public functions still carrying the default PUBLIC EXECUTE - the same set
  -- anon already reaches through PostgREST, and anon additionally has table
  -- grants this role does not. So the auditor is strictly less privileged than a
  -- role whose key ships inside the app. Narrowing that shared surface is a
  -- separate piece of work and is recorded in docs/DRIVER_OPS_COVERAGE.md.
  GRANT USAGE ON SCHEMA driver_ops_audit TO driver_ops_auditor;
  GRANT EXECUTE ON FUNCTION driver_ops_audit.log_driver_operation_remote(uuid, text, text, text, text, jsonb)
    TO driver_ops_auditor;

  -- The project hostname, not 127.0.0.1, and this is not a preference. Every
  -- loopback form (127.0.0.1 and localhost, sslmode disable/prefer/require) was
  -- probed against this instance: all of them match a `trust` line in pg_hba, so
  -- the server never asks for a password, and dblink then refuses the connection
  -- outright - "non-superusers may only connect using credentials they provide".
  -- Being local is exactly what breaks it. db.<ref>.supabase.co:5432 authenticates
  -- the auditor over TLS and answers. Port 5432 direct, never the 6543 pooler,
  -- which can deadlock looping back into itself under saturation.
  --
  -- The host is therefore tied to this project ref. On a different project (or a
  -- local `db reset`) the secret will point somewhere unreachable, the emitter
  -- degrades to the no-op it already is without a secret, and
  -- driver_ops_audit_health() reports it.
  v_dsn := format(
    'postgresql://driver_ops_auditor:%s@db.eoksxkdssptgyqyywdju.supabase.co:5432/postgres?sslmode=require&connect_timeout=3',
    v_password
  );

  SELECT id INTO v_secret_id FROM vault.secrets WHERE name = 'driver_ops_audit_dsn';

  IF v_secret_id IS NULL THEN
    PERFORM vault.create_secret(
      v_dsn,
      'driver_ops_audit_dsn',
      'Loopback DSN for the autonomous driver operation failure audit. Provisioned by migration 20260909100100; the password is generated in-block and never printed.'
    );
  ELSE
    PERFORM vault.update_secret(v_secret_id, v_dsn);
  END IF;
END;
$provision$;

-- ---------------------------------------------------------------------------
-- Point the emitter at the receiver instead of inserting directly
-- ---------------------------------------------------------------------------

-- The original body ran a raw INSERT, which only works when the DSN connects as
-- a role that owns the table or bypasses RLS. driver_ops_auditor deliberately is
-- neither, so the loopback now calls the SECURITY DEFINER receiver. The
-- signature, the early return when the secret is absent, and the
-- swallow-everything handler are unchanged.
CREATE OR REPLACE FUNCTION public.log_driver_operation_autonomous(
  p_driver_id     uuid,
  p_category      text,
  p_operation_key text,
  p_source_name   text,
  p_error_code    text,
  p_context       jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_dsn text;
BEGIN
  IF p_driver_id IS NULL THEN
    RETURN;
  END IF;

  SELECT decrypted_secret INTO v_dsn
  FROM vault.decrypted_secrets
  WHERE name = 'driver_ops_audit_dsn';

  IF v_dsn IS NULL THEN
    RETURN;
  END IF;

  -- format(%L) quotes every argument, so an error code or context carried out of
  -- a failing RPC cannot inject SQL into the loopback statement.
  PERFORM extensions.dblink_exec(
    v_dsn,
    format(
      'select driver_ops_audit.log_driver_operation_remote(%L, %L, %L, %L, %L, %L::jsonb)',
      p_driver_id, p_category, p_operation_key, p_source_name,
      p_error_code, coalesce(p_context, '{}'::jsonb)
    ),
    false   -- fail_on_error = false
  );
EXCEPTION WHEN others THEN
  RETURN;
END;
$$;

REVOKE ALL ON FUNCTION public.log_driver_operation_autonomous(
  uuid, text, text, text, text, jsonb
) FROM PUBLIC, anon, authenticated;

COMMENT ON FUNCTION public.log_driver_operation_autonomous(
  uuid, text, text, text, text, jsonb
) IS
  'Writes a failure audit row over a dblink loopback (as driver_ops_auditor, via driver_ops_audit.log_driver_operation_remote) so it survives the caller RAISE-triggered rollback. Low-volume allowlist only - never call from driver_report_location or driver_heartbeat.';
